version: 0.2

env:
  parameter-store:
    GITHUB_ACCESS_TOKEN: "/github/access_token"

phases:
  install:
    commands:
      - PR_NO=$(echo ${CODEBUILD_WEBHOOK_TRIGGER} | sed sed s_pr/__g)
  build:
    commands:
      - echo '=== build executed ==='
      - echo 'trigged by pr update'
